### ISSUE TITLE
Game locks up on "Creating World..."

### ISSUE THREAD

**Issue by DeveloperMCD** [Jerenaux/phaserquest#10]
I have the server running OK, and the client seems to load. I type in a character and click "new game". But then the game basically locks up on the phrase "Creating World..."

Is there something I have to do to initialize the Mongo DB? I have Mongo DB installed on the default port and everything. I also made sure all the ports were open on the firewall, etc.

Is there any configuration that needs to be done, to get this to run on a particular server install?

**Comment by Jerenaux** [comment]
Nope, normally everything works out of the box (if you have all the necessary things installed, which seems to be your case).

Is there any output from the server in the console?

**Comment by DeveloperMCD** [comment]
No, there is no output on the console.

**Comment by Jerenaux** [comment]
Just to be sure, I mean the node.js console, not the browser console?
