### ISSUE TITLE
Chat system not working

### ISSUE THREAD

**Issue by marius-m2** [Jerenaux/phaserquest#5]
Hey,

Been having some issues with chat messages not being sent through by the server.
So this bit 
        rooms.forEach(function(room){
            socket.broadcast.to(room).emit('chat', {id:playerID,txt:txt});
        });
doesn't seem to work for me.

Any ideas?

**Comment by marius-m2** [comment]
It works fine by replacing the rooms logic with io.emit, but I'm wondering what's running on your example page then, if the source doesn't allow chatting at this moment.

**Comment by Jerenaux** [comment]
I just pushed a commit to fix it. Several commits ago, I had deleted some code, thinking it wasn't used anymore, but it was actually the code used to manage rooms, which the chat uses. I had forgotten about this and didn't take time to check. Now it should be fixed, it works on my side, if you can confirm to me it works for you I'll close the issue. Thanks for notifying me!

**Comment by marius-m2** [comment]
Works great :) 
many thanks
