### ISSUE TITLE
How to edit the sprites 

### ISSUE THREAD

**Issue by joaompinto** [Jerenaux/phaserquest#7]
Is there a specific tool that we can use to easily edit the sprites JSON and PNG, or are there some kind of atlas format files missing ?

**Comment by Jerenaux** [comment]
I don't have a tool to edit existing atlases, but to create them I used a slightly adapter version of a python script called Pypacker, from https://github.com/jwezorek/pypacker . My workflow was to put all the assets of an atlas within a directory, and to pack the content of the directory together. If you want I can add these scripts to the repository, I would just need to order them a bit.

**Comment by joaompinto** [comment]
As I am planning to replace most of the assets (I have a very specific idea for a MMO survival game) I will just use pypacker and incrementally move to the new atlas. Anyway when you have the time I think it would be a good idea to have the assets / atlas build script on the repository. That would allow for sprite assets contribution, which is kind of hard to do now.  BTW thanks for your great  work on the code, documentation, and description of the MMO main issues with the development of Phaser Quest.

**Comment by Pastew** [comment]
Hi @joaompinto ,

Did you manage to achieve what you mentioned above?
If so, could you share it?

**Comment by joaompinto** [comment]
@Pastew I was not able to do it, meanwhile abandoned the project :(
